#!/usr/bin/env python3
"""Convert the compiled TASM fonts (source/engine/1sp/asm/1sp_af{hi,lo}.asm) to bitmap tables.

The original fonts are code: one routine per glyph that writes the ink colour at byte offsets
from the glyph's top-left pixel (OnePixel/TwoPixels/ThreePixels/FourPixels pos) and moves down
with NewLine (one line) or Skip2Lines (two). Several labels may precede one routine, and a
routine runs on to the next `ret`. The table of `dd character_NNN` at the font label maps
character codes to routines.

This script executes every routine symbolically and writes source/engine/1sp/1sp_font.cpp with
one bitmask per glyph row (bit n = pixel n). Run it from anywhere; it is a one-off, and the
generated file is committed.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
ASM = ROOT / 'source/engine/1sp/asm'
OUT = ROOT / 'source/engine/1sp/1sp_font.cpp'
WIDTH = {'OnePixel': 1, 'TwoPixels': 2, 'ThreePixels': 3, 'FourPixels': 4}


def parse(path, font_label):
    code = []     # ('label', name) | ('pix', pos, width) | ('lines', n) | ('ret',)
    table = []
    in_table = False
    for raw in path.read_text(encoding='utf-8').splitlines():
        line = raw.split(';')[0].strip()
        if not line:
            continue
        if line == font_label + ':':
            in_table = True
            continue
        if in_table:
            m = re.match(r'dd\s+(character_\d+)$', line)
            if m:
                table.append(m.group(1))
            continue
        m = re.match(r'(character_\d+):$', line)
        if m:
            code.append(('label', m.group(1)))
            continue
        m = re.match(r'(OnePixel|TwoPixels|ThreePixels|FourPixels)\s+(\d+)$', line)
        if m:
            code.append(('pix', int(m.group(2)), WIDTH[m.group(1)]))
        elif line == 'NewLine':
            code.append(('lines', 1))
        elif line == 'Skip2Lines':
            code.append(('lines', 2))
        elif line == 'ret':
            code.append(('ret',))
    assert len(table) == 256, (path, len(table))
    glyphs = {}
    for i, item in enumerate(code):
        if item[0] != 'label':
            continue
        row, pixels = 0, set()
        for op in code[i + 1:]:
            if op[0] == 'ret':
                break
            if op[0] == 'lines':
                row += op[1]
            elif op[0] == 'pix':
                pixels.update((row, op[1] + k) for k in range(op[2]))
        glyphs[item[1]] = pixels
    return [glyphs[label] for label in table]


def rows_of(glyphs):
    height = 1 + max((r for g in glyphs for r, _ in g), default=0)
    width = 1 + max((c for g in glyphs for _, c in g), default=0)
    assert width <= 16
    rows = []
    for g in glyphs:
        masks = [0] * height
        for r, c in g:
            masks[r] |= 1 << c
        rows.append(masks)
    return height, width, rows


def emit(name, glyphs):
    height, width, rows = rows_of(glyphs)
    out = [f'// {name}: {height} rows, up to {width} pixels wide.',
           f'static const unsigned short {name}_rows[256][{height}] = {{']
    for code, masks in enumerate(rows):
        out.append('  {' + ','.join(f'0x{m:03x}' for m in masks) + f'}},  // {code}')
    out.append('};')
    return height, '\n'.join(out)


def main():
    hi_height, hi = emit('font_hi', parse(ASM / '1sp_afhi.asm', 'font_hi'))
    lo_height, lo = emit('font_lo', parse(ASM / '1sp_aflo.asm', 'font_lo'))
    OUT.write_text(f'''// Generated by tools/fonts/convert_fonts.py from asm/1sp_afhi.asm and asm/1sp_aflo.asm.
// Do not edit; rerun the script instead.
//
// The original fonts were compiled code, one routine per glyph; these tables hold the same
// pixels as one bitmask per row (bit n = pixel n from the glyph's left edge).

#include "1sp_hdrs.h"

{hi}

{lo}

// Identify the two fonts by address, as the original passed the address of the routine table.
extern "C" char font_hi;
extern "C" char font_lo;
char font_hi;
char font_lo;

// Was a call into the glyph routine: writes the ink colour (the low byte of color) for every set
// pixel, with llen bytes between lines (negative when the screen is upside down).
extern "C" void _font_put_char (void *font, int c, unsigned char *p, int llen, int color)
{{
  const unsigned short *rows;
  int height;
  if (font==&font_hi)
  {{
    rows=font_hi_rows[c&255];
    height={hi_height};
  }}
  else
  {{
    rows=font_lo_rows[c&255];
    height={lo_height};
  }}
  unsigned char ink=(unsigned char)color;
  for (int r=0; r<height; r++, p+=llen)
    for (unsigned mask=rows[r], x=0; mask!=0; mask>>=1, x++)
      if (mask&1)
        p[x]=ink;
}}
''', encoding='utf-8')
    print(f'wrote {OUT}: font_hi {hi_height} rows, font_lo {lo_height} rows')


if __name__ == '__main__':
    main()
