// Generated by tools/layout/stale_memory.py from clang's 32-bit MSVC record layouts. Do not edit.
//
// For each game object class that reaches offset 232 (ACannon::global_time in the original's
// layout), the bytes it holds at offsets 232-235, read from the port's object. Classes
// that end before that offset leave the word alone. See stale.h.

#include <typeinfo>

#include "headers.h"

const int Stale_memory::offset=232;

void Stale_memory::copy_word (Object *o, unsigned char *w)
{
  const std::type_info &type=typeid(*o);
  if (type==typeid(ACannon))  // ACannon::global_time
  {
    copy(w,0,&dynamic_cast<ACannon*>(o)->global_time,0,4);
  }
  else if (type==typeid(AlienChgun))  // AlienChgun::body[7].vy
  {
    copy(w,0,&dynamic_cast<AlienChgun*>(o)->body[7].vy,0,4);
  }
  else if (type==typeid(AlienSmoke))  // AlienSmoke::table[10].x, AlienSmoke::table[10].y
  {
    copy(w,0,&dynamic_cast<AlienSmoke*>(o)->table[10].x,0,2);
    copy(w,2,&dynamic_cast<AlienSmoke*>(o)->table[10].y,0,2);
  }
  else if (type==typeid(ChGun))  // ChGun::body[6].x
  {
    copy(w,0,&dynamic_cast<ChGun*>(o)->body[6].x,0,4);
  }
  else if (type==typeid(Collect))  // Posit vftable/vbtable pointer
  {
    address(w,0,1,0,4);
  }
  else if (type==typeid(Destroy))  // Destroy::blow
  {
    copy(w,0,&dynamic_cast<Destroy*>(o)->blow,0,4);
  }
  else if (type==typeid(Destsmoke))  // Destsmoke::plane
  {
    copy(w,0,&dynamic_cast<Destsmoke*>(o)->plane,0,4);
  }
  else if (type==typeid(Fog))  // Posit::fracty
  {
    copy(w,0,&dynamic_cast<Posit*>(o)->fracty,0,4);
  }
  else if (type==typeid(MBoss1))  // Move::vy
  {
    copy(w,0,&dynamic_cast<Move*>(o)->vy,0,4);
  }
  else if (type==typeid(Mine))  // Posit vftable/vbtable pointer
  {
    address(w,0,1,0,4);
  }
  else if (type==typeid(MorphDest))  // Posit::counted_kstat_down
  {
    copy(w,0,&dynamic_cast<Posit*>(o)->counted_kstat_down,0,4);
  }
  else if (type==typeid(MyBomb))  // MyBomb::buffer[16].phase, MyBomb::buffer[17].x; the other bytes are padding
  {
    copy(w,0,&dynamic_cast<MyBomb*>(o)->buffer[16].phase,0,1);
    copy(w,2,&dynamic_cast<MyBomb*>(o)->buffer[17].x,0,2);
  }
  else if (type==typeid(MyCannon))  // Posit::fracty
  {
    copy(w,0,&dynamic_cast<Posit*>(o)->fracty,0,4);
  }
  else if (type==typeid(Myship))  // Myship::weapon (pointer)
  {
    address(w,0,dynamic_cast<Myship*>(o)->weapon!=NULL,0,4);
  }
  else if (type==typeid(NetMine))  // Posit::x
  {
    copy(w,0,&dynamic_cast<Posit*>(o)->x,0,4);
  }
  else if (type==typeid(Plask))  // Plask::body[7].vy
  {
    copy(w,0,&dynamic_cast<Plask*>(o)->body[7].vy,0,4);
  }
  else if (type==typeid(Raft))  // Sound::smp (pointer)
  {
    address(w,0,dynamic_cast<Sound*>(o)->smp!=NULL,0,4);
  }
  else if (type==typeid(Simple1))  // Move::vy
  {
    copy(w,0,&dynamic_cast<Move*>(o)->vy,0,4);
  }
  else if (type==typeid(Simple3))  // Move::vy
  {
    copy(w,0,&dynamic_cast<Move*>(o)->vy,0,4);
  }
  else if (type==typeid(Splinters))  // Splinters::table[7].y
  {
    copy(w,0,&dynamic_cast<Splinters*>(o)->table[7].y,0,4);
  }
  else if (type==typeid(Taran))  // Move::vy
  {
    copy(w,0,&dynamic_cast<Move*>(o)->vy,0,4);
  }
  else if (type==typeid(Thief))  // Sound::smp (pointer)
  {
    address(w,0,dynamic_cast<Sound*>(o)->smp!=NULL,0,4);
  }
  else if (type==typeid(Unblock))  // Posit::y
  {
    copy(w,0,&dynamic_cast<Posit*>(o)->y,0,4);
  }
  else if (type==typeid(User))  // User::buffer[124], User::buffer[125], User::buffer[126], User::buffer[127]
  {
    copy(w,0,&dynamic_cast<User*>(o)->buffer[124],0,1);
    copy(w,1,&dynamic_cast<User*>(o)->buffer[125],0,1);
    copy(w,2,&dynamic_cast<User*>(o)->buffer[126],0,1);
    copy(w,3,&dynamic_cast<User*>(o)->buffer[127],0,1);
  }
  else if (type==typeid(Wave))  // Wave::table[13].y, Wave::table[13].phase; the other bytes are padding
  {
    copy(w,0,&dynamic_cast<Wave*>(o)->table[13].y,0,2);
    copy(w,2,&dynamic_cast<Wave*>(o)->table[13].phase,0,1);
  }
}
